title: Blog - strehl.dev
author: Bernd Strehl
email: bernd@strehl.dev
description: > # this means to ignore newlines until "baseurl:"
  After 2.5 years of web3 I returned back to web2 as a serverless developer. I learned
  technical details about cryptocurrencies and blockchains in recent time and use this site
  to educate people about it.
theme: minima

# social links
twitter_username: strehldev # DO NOT include the @ character, or else the build will fail!
github_username:  strernd # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
